//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialFund
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int Coins { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public int Group_UserId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Group_User Group_User { get; set; }
    }
}
