//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Log
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Input coins.")]
        public decimal Coins { get; set; }
        public System.DateTime Date { get; set; }

        [Required(ErrorMessage = "Input coins.")]
        public string Comment { get; set; }
        public int Group_UserId { get; set; }
    
        public virtual Group_User Group_User { get; set; }
    }
}
